### ISSUE TITLE
rtcontrol: error: no such option: --json

### ISSUE THREAD

**Issue by mafrosis** [pyroscope/pyrocore#21]
The [docs](http://pyrocore.readthedocs.io/en/latest/howto.html) tell me there's a machine-readable flag `--json` on `rtcontrol`, but it's not available in my install of `pyrocore==0.4.2`

**Comment by mafrosis** [comment]
I see the `--json` flag was introduced in 6d45e554, which presumably is after the 0.4.2 release. Without tags it's difficult to reconcile source against released version..

**Comment by mafrosis** [comment]
Possibly related to #23, just after fresh install from HEAD:

    > rtcontrol '*'
    Traceback (most recent call last):
      File "/tmp/pyrocore/bin/rtcontrol", line 9, in <module>
        load_entry_point('pyrocore==0.4.3.dev20160626', 'console_scripts', 'rtcontrol')()
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
        return ep.load()
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/scripts/rtcontrol.py", line 31, in <module>
        from pyrocore.torrent import engine, formatting
      File "/tmp/pyrocore/local/lib/python2.7/site-packages/pyrocore/torrent/formatting.py", line 26, in <module>
        from pyrobase import templating
    ImportError: cannot import name templating
